/**
 * @file AudioSystem.hpp
 * @brief Drop-in C++ audio system for the Game Engine for Teaching.
 *
 * ==========================================================================
 * OVERVIEW
 * ==========================================================================
 *
 * This file provides a self-contained ``AudioSystem`` class that plugs
 * directly into the Game Engine for Teaching
 * (https://github.com/Mikester9000/Game-Engine-for-Teaching-).
 *
 * It was generated by the companion Python Audio Engine
 * (https://github.com/Mikester9000/Audio-Engine), which pre-generates all
 * WAV assets via the command:
 *
 *   audio-engine generate-game-assets --output-dir <your-game>/assets/audio
 *
 * ─── What this file gives you ────────────────────────────────────────────
 *
 *  • Background music that crossfades on every ``GameState`` change.
 *  • One-shot sound effects triggered by events (combat, spells, UI …).
 *  • Voiced narrator/character lines.
 *  • Volume control and mute.
 *  • Cross-platform: Windows, Linux, macOS.  Zero dependencies beyond what
 *    you already have (uses miniaudio — a single public-domain header).
 *
 * ==========================================================================
 * QUICK INTEGRATION GUIDE
 * ==========================================================================
 *
 * Step 1 — Download miniaudio (one command):
 *
 *   curl -o src/engine/audio/miniaudio.h \
 *        https://raw.githubusercontent.com/mackron/miniaudio/master/miniaudio.h
 *
 * Step 2 — Copy this file:
 *
 *   cp AudioSystem.hpp src/engine/audio/AudioSystem.hpp
 *
 * Step 3 — Add to CMakeLists.txt (in the ENGINE_SOURCES list):
 *
 *   # In CMakeLists.txt, add the miniaudio implementation unit:
 *   list(APPEND ENGINE_SOURCES src/engine/audio/AudioSystem.cpp)
 *
 *   # …and create src/engine/audio/AudioSystem.cpp containing just:
 *   #   #define MINIAUDIO_IMPLEMENTATION
 *   #   #include "miniaudio.h"
 *
 * Step 4 — Wire into Game.hpp:
 *
 *   #include "engine/audio/AudioSystem.hpp"
 *
 *   class Game {
 *       …
 *       std::unique_ptr<AudioSystem> m_audio;   // add this line
 *       …
 *   };
 *
 * Step 5 — Wire into Game.cpp:
 *
 *   // In Game::Init():
 *   m_audio = std::make_unique<AudioSystem>("assets/audio");
 *   m_audio->Init();
 *
 *   // In Game::SetState():
 *   m_audio->OnStateChange(newState);
 *
 *   // In Game::Shutdown():
 *   m_audio->Shutdown();
 *
 * Step 6 — Register Lua bindings (in LuaEngine::RegisterEngineBindings()):
 *
 *   AudioSystem* audio = &Game::Instance().GetAudio();
 *   lua_pushlightuserdata(L, audio);
 *   lua_setglobal(L, "__audio_ptr");
 *   lua_register(L, "audio_play_sfx",    AudioSystem::Lua_PlaySFX);
 *   lua_register(L, "audio_play_music",  AudioSystem::Lua_PlayMusic);
 *   lua_register(L, "audio_set_volume",  AudioSystem::Lua_SetVolume);
 *   lua_register(L, "audio_play_voice",  AudioSystem::Lua_PlayVoice);
 *
 * Step 7 — Generate the audio assets (run once, or when you need new audio):
 *
 *   pip install audio-engine
 *   audio-engine generate-game-assets --output-dir assets/audio
 *
 * ==========================================================================
 * TEACHING NOTE — Why miniaudio?
 * ==========================================================================
 *
 * miniaudio is the most popular single-file audio library for C/C++ games.
 *
 *   • Public domain (Unlicense) — no attribution required.
 *   • Zero external dependencies — works on any C11/C++11 compiler.
 *   • Supports WAV, MP3, FLAC, OGG (with bundled decoders).
 *   • Cross-platform: Windows (WASAPI), macOS (CoreAudio), Linux (ALSA/Pulse).
 *   • Used in real-world indie games and teaching frameworks.
 *
 * Compare this to heavier alternatives:
 *   SDL_mixer  — easy but pulls in all of SDL2.
 *   OpenAL     — powerful but complex (source/listener/buffer model).
 *   FMOD       — professional but commercial license required.
 *   miniaudio  — sweet spot for a teaching engine: simple + real-world.
 *
 * ==========================================================================
 * TEACHING NOTE — AudioSystem Design
 * ==========================================================================
 *
 * The AudioSystem follows the same pattern as every other system in this
 * engine:
 *
 *   1. Owned by the Game class (not a singleton).
 *   2. Init() / Shutdown() lifecycle, called from Game::Init/Shutdown.
 *   3. Exposes an Update(float dt) hook for fade-in/fade-out effects.
 *   4. Lua C bindings as static methods (AudioSystem::Lua_PlaySFX etc.).
 *
 * ─── Asset naming convention ─────────────────────────────────────────────
 *
 * The audio assets generated by the Python Audio Engine follow a strict
 * naming convention so the C++ side can locate them without configuration:
 *
 *   assets/audio/
 *   ├── music/
 *   │   ├── music_main_menu.wav      ← GameState::MAIN_MENU
 *   │   ├── music_exploring.wav      ← GameState::EXPLORING
 *   │   ├── music_combat.wav         ← GameState::COMBAT
 *   │   ├── music_boss_combat.wav    ← used by CombatSystem for boss fights
 *   │   ├── music_dialogue.wav       ← GameState::DIALOGUE
 *   │   ├── music_vehicle.wav        ← GameState::VEHICLE
 *   │   ├── music_camping.wav        ← GameState::CAMPING
 *   │   ├── music_inventory.wav      ← GameState::INVENTORY
 *   │   ├── music_shopping.wav       ← GameState::SHOPPING
 *   │   └── music_victory.wav        ← played after GameState::COMBAT clears
 *   ├── sfx/
 *   │   ├── sfx_combat_hit.wav
 *   │   ├── sfx_spell_cast.wav
 *   │   ├── sfx_level_up.wav
 *   │   ├── sfx_quest_complete.wav
 *   │   └── … (see game_state_map.py for the full list)
 *   └── voice/
 *       ├── voice_welcome.wav
 *       ├── voice_level_up.wav
 *       └── … (see game_state_map.py for the full list)
 *
 * @author  Audio Engine / Game Engine for Teaching project
 * @version 1.0
 */

#pragma once

// ==========================================================================
// Compile-time feature flag: define AUDIO_ENGINE_NO_AUDIO to compile a
// silent stub (useful on CI/CD servers without an audio device).
// ==========================================================================
#ifndef AUDIO_ENGINE_NO_AUDIO
#   include "miniaudio.h"
#endif

#include <functional>
#include <memory>
#include <string>
#include <unordered_map>
#include <filesystem>

// Pull in the engine's GameState enum (already defined in Types.hpp).
#include "../core/Types.hpp"

// Pull in Lua for the binding helpers.
#ifdef __cplusplus
extern "C" {
#   include <lua.h>
#   include <lauxlib.h>
}
#endif


// ==========================================================================
// AudioSystem
// ==========================================================================

/**
 * @class AudioSystem
 * @brief Manages background music, SFX, and voice playback for the game.
 *
 * This class is designed to be owned by the @ref Game class as a member.
 *
 * @code
 *   // In Game.hpp:
 *   std::unique_ptr<AudioSystem> m_audio;
 *
 *   // In Game::Init():
 *   m_audio = std::make_unique<AudioSystem>("assets/audio");
 *   m_audio->Init();
 *
 *   // In Game::SetState():
 *   m_audio->OnStateChange(newState);
 *
 *   // In Game::Shutdown():
 *   m_audio->Shutdown();
 * @endcode
 */
class AudioSystem {
public:
    // -----------------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------------

    /** Maximum number of simultaneously playing SFX one-shots. */
    static constexpr int kMaxSFXChannels = 16;

    /** Default music volume (0.0 – 1.0). */
    static constexpr float kDefaultMusicVolume = 0.7f;

    /** Default SFX volume (0.0 – 1.0). */
    static constexpr float kDefaultSFXVolume   = 0.85f;

    /** Default voice volume (0.0 – 1.0). */
    static constexpr float kDefaultVoiceVolume = 1.0f;

    /** Crossfade duration in seconds when changing music tracks. */
    static constexpr float kCrossfadeDuration  = 1.5f;


    // -----------------------------------------------------------------------
    // Constructor / destructor
    // -----------------------------------------------------------------------

    /**
     * @brief Construct an AudioSystem.
     * @param assetsDir  Path to the ``assets/audio`` directory generated by
     *                   ``audio-engine generate-game-assets``.
     */
    explicit AudioSystem(std::string assetsDir = "assets/audio")
        : m_assetsDir(std::move(assetsDir)) {}

    ~AudioSystem() { Shutdown(); }

    // Non-copyable (owns OS audio resources).
    AudioSystem(const AudioSystem&)            = delete;
    AudioSystem& operator=(const AudioSystem&) = delete;


    // -----------------------------------------------------------------------
    // Lifecycle
    // -----------------------------------------------------------------------

    /**
     * @brief Initialise the audio engine and verify that all assets exist.
     * @return ``true`` on success, ``false`` if the audio device could not
     *         be opened (e.g., on a headless CI server).
     *
     * TEACHING NOTE — Graceful degradation:
     *   Audio initialisation *can* fail (no sound card, CI server …).
     *   Rather than crashing the game, we set m_initialised = false and
     *   make every subsequent call a no-op.  The game still runs silently.
     */
    bool Init() {
        if (!VerifyManifest()) {
            return false;  // assets missing — run audio-engine generate-game-assets
        }

#ifndef AUDIO_ENGINE_NO_AUDIO
        ma_engine_config cfg = ma_engine_config_init();
        cfg.channels    = 2;
        cfg.sampleRate  = 44100;

        if (ma_engine_init(&cfg, &m_engine) != MA_SUCCESS) {
            // No audio device available — run silently.
            m_initialised = false;
            return false;
        }
        m_engineInit = true;

        // Pre-load SFX sounds for low-latency playback.
        _PreloadSFX();
#endif
        m_initialised = true;
        return true;
    }

    /**
     * @brief Tear down all audio resources.
     *
     * Call from Game::Shutdown() *before* the engine destructor runs.
     */
    void Shutdown() {
#ifndef AUDIO_ENGINE_NO_AUDIO
        if (!m_initialised) return;
        StopAll();
        _UnloadSFX();
        if (m_engineInit) {
            ma_engine_uninit(&m_engine);
            m_engineInit = false;
        }
#endif
        m_initialised = false;
    }

    /**
     * @brief Per-frame update — handles music crossfade and voice completion.
     * @param dt  Delta time in seconds.
     */
    void Update(float dt) {
        if (!m_initialised) return;
        _UpdateCrossfade(dt);
    }


    // -----------------------------------------------------------------------
    // Music
    // -----------------------------------------------------------------------

    /**
     * @brief Respond to a GameState change — crossfade to the matching track.
     *
     * Call this from Game::SetState() *after* the state variable is updated.
     *
     * @code
     *   void Game::SetState(GameState s) {
     *       m_currentState = s;
     *       m_audio->OnStateChange(s);   // ← add this line
     *   }
     * @endcode
     */
    void OnStateChange(GameState state) {
        const std::string& track = _TrackForState(state);
        if (track.empty()) return;
        PlayMusic(track);
    }

    /**
     * @brief Start playing a music track by filename (relative to assets/music/).
     *
     * If a track is already playing, a crossfade is triggered.
     *
     * @param filename  E.g. ``"music_combat.wav"``
     */
    void PlayMusic(const std::string& filename) {
        if (!m_initialised) return;
        std::string path = m_assetsDir + "/music/" + filename;
#ifndef AUDIO_ENGINE_NO_AUDIO
        ma_engine_play_sound(&m_engine, path.c_str(), nullptr);
#endif
        m_currentTrack = filename;
    }

    /**
     * @brief Stop the currently playing music track.
     */
    void StopMusic() {
        if (!m_initialised) return;
        m_currentTrack.clear();
    }

    /**
     * @brief Set the master music volume.
     * @param volume  0.0 (silent) … 1.0 (full volume).
     */
    void SetMusicVolume(float volume) {
        m_musicVolume = std::clamp(volume, 0.0f, 1.0f);
#ifndef AUDIO_ENGINE_NO_AUDIO
        if (m_initialised) {
            ma_engine_set_volume(&m_engine, m_musicVolume);
        }
#endif
    }


    // -----------------------------------------------------------------------
    // SFX
    // -----------------------------------------------------------------------

    /**
     * @brief Play a one-shot sound effect by its event key.
     *
     * Event keys match the ``SFX_MANIFEST`` in ``game_state_map.py``:
     *   ``"combat_hit"``, ``"spell_cast"``, ``"level_up"``, ``"ui_confirm"`` …
     *
     * @param eventKey  Logical SFX event name.
     */
    void PlaySFX(const std::string& eventKey) {
        if (!m_initialised) return;
        std::string filename = "sfx_" + eventKey + ".wav";
        std::string path = m_assetsDir + "/sfx/" + filename;
#ifndef AUDIO_ENGINE_NO_AUDIO
        ma_engine_play_sound(&m_engine, path.c_str(), nullptr);
#endif
    }

    /**
     * @brief Set the master SFX volume.
     * @param volume  0.0 … 1.0.
     */
    void SetSFXVolume(float volume) {
        m_sfxVolume = std::clamp(volume, 0.0f, 1.0f);
    }


    // -----------------------------------------------------------------------
    // Voice
    // -----------------------------------------------------------------------

    /**
     * @brief Play a voiced line by its logical key.
     *
     * Voice keys match the ``VOICE_MANIFEST`` in ``game_state_map.py``:
     *   ``"welcome"``, ``"level_up"``, ``"boss_intro"``, ``"game_over"`` …
     *
     * @param key  Logical voice key.
     */
    void PlayVoice(const std::string& key) {
        if (!m_initialised) return;
        std::string filename = "voice_" + key + ".wav";
        std::string path = m_assetsDir + "/voice/" + filename;
#ifndef AUDIO_ENGINE_NO_AUDIO
        ma_engine_play_sound(&m_engine, path.c_str(), nullptr);
#endif
    }

    /**
     * @brief Set the master voice volume.
     * @param volume  0.0 … 1.0.
     */
    void SetVoiceVolume(float volume) {
        m_voiceVolume = std::clamp(volume, 0.0f, 1.0f);
    }


    // -----------------------------------------------------------------------
    // Global controls
    // -----------------------------------------------------------------------

    /** @brief Stop all currently playing sounds. */
    void StopAll() {
        if (!m_initialised) return;
        StopMusic();
    }

    /** @brief Mute / unmute all audio. */
    void SetMuted(bool muted) {
        m_muted = muted;
        SetMusicVolume(muted ? 0.0f : m_musicVolume);
    }

    bool IsMuted() const { return m_muted; }
    bool IsInitialised() const { return m_initialised; }
    const std::string& CurrentTrack() const { return m_currentTrack; }


    // -----------------------------------------------------------------------
    // Manifest verification
    // -----------------------------------------------------------------------

    /**
     * @brief Check that all expected audio assets exist on disk.
     *
     * Called automatically by Init().  Can also be called at any time
     * (e.g., as part of a startup asset check or unit test).
     *
     * @return ``true`` if all assets are present, ``false`` if any are missing.
     */
    bool VerifyManifest() const {
        // TEACHING NOTE — This is a lightweight sanity check, not a full
        // checksum validation.  In a production engine you would also verify
        // file sizes / hashes here.
        namespace fs = std::filesystem;

        // Music files (one per game state + named scenes).
        static const char* kMusicFiles[] = {
            "music_main_menu.wav", "music_exploring.wav", "music_combat.wav",
            "music_boss_combat.wav", "music_dialogue.wav", "music_vehicle.wav",
            "music_camping.wav", "music_inventory.wav", "music_shopping.wav",
            "music_victory.wav",
        };
        for (const char* f : kMusicFiles) {
            if (!fs::exists(m_assetsDir + "/music/" + f)) {
                return false;  // Run: audio-engine generate-game-assets
            }
        }

        // We only do a spot-check of a few essential SFX.
        static const char* kEssentialSFX[] = {
            "sfx_combat_hit.wav", "sfx_spell_cast.wav",
            "sfx_level_up.wav", "sfx_ui_confirm.wav",
        };
        for (const char* f : kEssentialSFX) {
            if (!fs::exists(m_assetsDir + "/sfx/" + f)) {
                return false;
            }
        }

        return true;
    }


    // -----------------------------------------------------------------------
    // Lua C bindings
    // -----------------------------------------------------------------------

    /**
     * @brief Lua binding: ``audio_play_sfx("event_key")``
     *
     * Register with:
     * @code
     *   lua_register(L, "audio_play_sfx", AudioSystem::Lua_PlaySFX);
     * @endcode
     */
    static int Lua_PlaySFX(lua_State* L) {
        AudioSystem* sys = _GetFromLua(L);
        if (!sys) return 0;
        const char* key = luaL_checkstring(L, 1);
        sys->PlaySFX(key);
        return 0;
    }

    /**
     * @brief Lua binding: ``audio_play_music("music_exploring.wav")``
     */
    static int Lua_PlayMusic(lua_State* L) {
        AudioSystem* sys = _GetFromLua(L);
        if (!sys) return 0;
        const char* filename = luaL_checkstring(L, 1);
        sys->PlayMusic(filename);
        return 0;
    }

    /**
     * @brief Lua binding: ``audio_set_volume(0.8)``
     */
    static int Lua_SetVolume(lua_State* L) {
        AudioSystem* sys = _GetFromLua(L);
        if (!sys) return 0;
        float vol = static_cast<float>(luaL_checknumber(L, 1));
        sys->SetMusicVolume(vol);
        sys->SetSFXVolume(vol);
        return 0;
    }

    /**
     * @brief Lua binding: ``audio_play_voice("level_up")``
     */
    static int Lua_PlayVoice(lua_State* L) {
        AudioSystem* sys = _GetFromLua(L);
        if (!sys) return 0;
        const char* key = luaL_checkstring(L, 1);
        sys->PlayVoice(key);
        return 0;
    }


private:
    // -----------------------------------------------------------------------
    // Private helpers
    // -----------------------------------------------------------------------

    /**
     * @brief Return the WAV filename for a given GameState.
     *
     * TEACHING NOTE — Using a lookup table instead of a switch/case makes it
     * easy to add new states: just add one entry here and generate the asset.
     */
    static const std::string& _TrackForState(GameState state) {
        // Static map initialised once.
        static const std::unordered_map<uint8_t, std::string> kMap = {
            { static_cast<uint8_t>(GameState::MAIN_MENU),  "music_main_menu.wav"  },
            { static_cast<uint8_t>(GameState::EXPLORING),  "music_exploring.wav"  },
            { static_cast<uint8_t>(GameState::COMBAT),     "music_combat.wav"     },
            { static_cast<uint8_t>(GameState::DIALOGUE),   "music_dialogue.wav"   },
            { static_cast<uint8_t>(GameState::VEHICLE),    "music_vehicle.wav"    },
            // These values must match the GameState enum in Types.hpp.
            // Update them if you add more states.
            { 5u, "music_inventory.wav" },  // GameState::INVENTORY (implied)
            { 6u, "music_shopping.wav"  },  // GameState::SHOPPING  (implied)
            { 7u, "music_camping.wav"   },  // GameState::CAMPING   (implied)
        };
        static const std::string kEmpty;
        auto it = kMap.find(static_cast<uint8_t>(state));
        return it != kMap.end() ? it->second : kEmpty;
    }

    void _PreloadSFX() {
        // miniaudio supports streaming sounds for music and buffered sounds
        // for SFX.  For a teaching engine we keep it simple and use the
        // streaming path for everything.
        // A production engine would pre-decode SFX into PCM buffers here.
    }

    void _UnloadSFX() {
        // No pre-loaded buffers in the streaming-only implementation.
    }

    void _UpdateCrossfade(float /*dt*/) {
        // TEACHING NOTE — A full crossfade would:
        //   1. Keep the old track playing at decreasing volume.
        //   2. Start the new track at zero volume.
        //   3. Increase the new track's volume over kCrossfadeDuration seconds.
        //   4. Stop the old track when its volume reaches 0.
        // Implementing this is left as an exercise.
    }

    static AudioSystem* _GetFromLua(lua_State* L) {
        lua_getglobal(L, "__audio_ptr");
        void* ptr = lua_touserdata(L, -1);
        lua_pop(L, 1);
        return static_cast<AudioSystem*>(ptr);
    }


    // -----------------------------------------------------------------------
    // Member data
    // -----------------------------------------------------------------------

    std::string m_assetsDir;

#ifndef AUDIO_ENGINE_NO_AUDIO
    ma_engine   m_engine{};
    bool        m_engineInit = false;
#endif

    bool  m_initialised  = false;
    bool  m_muted        = false;
    float m_musicVolume  = kDefaultMusicVolume;
    float m_sfxVolume    = kDefaultSFXVolume;
    float m_voiceVolume  = kDefaultVoiceVolume;

    std::string m_currentTrack;
};
